---
title: "Untitled"
author: "Lium"
date: "12/9/2019"
output: html_document
---


```{r}
# import data
data<-read.csv("stemfinal.csv")
head(data)

attach(data)
```


## EDA
```{r}
# Stress
hist(na.omit(data$Stress), main = "Histogram of Stress Scores")
median(na.omit(data$Stress))
mean(na.omit(data$Stress))
```


## Remove the value "(blank)".
```{r}
data<-data[complete.cases(data[, "Stress"]),]
data<-data[complete.cases(data[, "FirstGen"]),]


```


## Recode STEM to zero and one
```{r}
Stress<-cut(Stress,breaks=3,labels=c("Low", "Average","High"))
summary(Stress)
plot(Stress)
```

## Fix levels
```{r}
levels(EFL)[1] <- NA
levels(FirstGen)[1] <- NA
levels(Transfer)[1] <- NA
```



## Examine frequencies
```{r}
table(Stress, Transfer, EFL, FirstGen)
```



## Nomial
```{r}
library(nnet)

##Set baseline stress to average
Stress2 <- relevel(Stress, ref = "Average")

m1 <- multinom(Stress2~Transfer+EFL+FirstGen+Transfer*EFL+Transfer*FirstGen+EFL*FirstGen)
summary(m1, Wald = TRUE)
```

## p-value
```{r}
z <- summary(m1)$coefficients/summary(m1)$standard.errors
z

p <- (1 - pnorm(abs(z), 0, 1))*2
p
```

## Analysis of Deviance
```{r}
library(car)
Anova(m1)
```

## Odds Ratios & CI
```{r}
exp(coef(m1))
confint(m1)
```

## Interpretation of odds ratios


- 



## Effect plots
```{r}
stress_lvl <- factor(Stress)
transfer_lvl <- factor(Transfer)
efl_lvl <- factor(EFL)
firstgen_lvl <- factor(FirstGen)

library(effects)
plot(allEffects(m1), ask = FALSE)
```













## Transfer, FirstGen, Freshman, Sexual Orientataion, EFL, GPA, STEM