---
title: "Missing values with R"
subtitle: "How to Check & Clean Missing Values / NA using R"
# author: "Kaixin Wang"
# date: "OSCR - Summer Session C 2019"
# output: rmarkdown::github_document
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

Import data:

```{r, message = F}
library(readr)
input = read_csv("person_info.csv")
input
```

Find the location of the NAs:

```{r}
idx = which(is.na(input))   # find the position of the NAs
idx   
```

Find the locations of the character “NA”, “na”, “N/A”, or “n/a”:

```{r}
# NAs = c("na", "n/a", "NA", "N/A")
nas = which(input$car_1 == "na" | input$car_1 == "n/a" | input$car_1 == "NA" | input$car_1 == "N/A")
nas
```

Find whether one row contains any missing values:

```{r}
complete.cases(input$car_1)
```

Impute the missing values with `NA`:

```{r}
input$car_1[nas] <- NA   # impute with NAs
input$car_1
```

Omit row(s) with missing value(s): 

```{r}
na.omit(input)   # remove rows that contain any NA
```

Typical approaches to handle missing values:

- impute with `NA`
- impute with the median/mean of the data 

To ignore missing values in calculations:

```{r}
# example:
vars <- c(10, 20, NA, 25, 5, 8, NA, 11)
mean(vars)   # NA introduced
mean(vars, na.rm = T)  # ignore the NAs and compute the summary statistics
```

